[default]
default_event_img_url = "https://www.example.de/openGraph-200x200.png"
enable_move_rss = true
destination_folder = "/examples/path"
enable_update_nextcloud_news = true
nextcloud_user_id = "userid"
rss_tld = "https://rss.rss_tld.org"
nextcloud_container_name = "nextcloud-aio-nextcloud"

[[rss_feeds]]
name = "buehne_veranstaltungen.rss"
title = "Bühne - Stuttgart"
category = 79078
[[rss_feeds]]
name = "philo_veranstaltungen.rss"
title = "Literatur, Philosophie und Geschichte - Stuttgart"
category = 77317
[[rss_feeds]]
name = "musik_veranstaltungen.rss"
title = "Musik - Stuttgart"
category = 79091