default:
  DEFAULT_IMAGE_URL: "https://www.stuttgart.de/openGraph-200x200.png"
  destination_folder: "/home/pi/rss_feeds"
  rss_feeds:
    - name: "buehne_veranstaltungen.rss"
      title: "Bühne - Stuttgart"
      category: 79078
    - name: "philo_veranstaltungen.rss"
      title: "Literatur, Philosophie und Geschichte - Stuttgart"
      category: 77317
    - name: "musik_veranstaltungen.rss"
      title: "Musik - Stuttgart"
      category: 79091
  nextcloud_user_id: "danielvolz"
  rss_tld: "https://rss.danielvolz.org"
  nextcloud_container_name: "nextcloud-aio-nextcloud"