name: Generate requirements.txt

on:
  push:
    branches:
      - main # Modify this based on your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate requirements.txt
        run: pip freeze > requirements.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "Daniel Volz"
          git config --global user.email "mail@danielvolz.org"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push
