name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: ryan-rozario/pipreqs-action-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: /home/pi/scripts/stuttgart_veranstaltungen_rss #default is the root of the repository
          REQUIREMENT_PATH: /home/pi/scripts/stuttgart_veranstaltungen_rss/requirements.txt #default is requirement.txt in the root of your repository
