name: Check requirements.txt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements.txt
        uses: ekvanox/pipreqs-action@master

        with:
          PROJECT_PATH: "/home/pi/scripts/stuttgart-veranstaltungen-rss"
          REQUIREMENT_PATH: "/home/pi/scripts/stuttgart-veranstaltungen-rss/reqs/requirements.txt"
          COMMIT_MESSAGE: "update/add requirements.txt"
